### PR TITLE
Test for and eliminate multiple usages of reset-ticks in the same procedure

### LINKED ISSUE #116: Most Connected Chemistry models have two calls to `reset-ticks` in `setup`
One at the top of `setup`, just after `clear-all`, and one at the end. The top ones should be removed...

In fact, it would make sense to write a test for multiple usages of `reset-ticks`. If there turns out to be legitimate cases (which I doubt) they can be added as exceptions.

### PR DESCRIPTION
**Pull request by nicolaspayette**
Fix #116.

### CODE REVIEW

File: src/test/scala/org/nlogo/models/CodeTests.scala [hunk 1]
```diff
@@ -191,6 +193,26 @@ class CodeTests extends TestModels {
     } yield model.quotedPath + "\n  " + nonLowerCaseTokens.mkString("\"", "\", \"", "\"")
   }
 
+  testLibraryModels("Procedures should not use `reset-ticks` more than once") { models =>
+    for {
+      model <- models
+      if !(model.is3d || model.code.contains("extensions"))
```
Comment (Idloj) [inline src/test/scala/org/nlogo/models/CodeTests.scala]: Why do you filter out 3d models and models using extensions?
